#!/bin/bash

# MarketHub Quick Start Guide
# Démarrage en 5 minutes

echo "🚀 MarketHub - Quick Start"
echo "=========================="
echo ""

# Check Node version
NODE_VERSION=$(node -v)
echo "✅ Node.js: $NODE_VERSION"

# Option to show
echo ""
echo "Choisir une option de démarrage:"
echo "1. Développement local (frontend + backend séparé)"
echo "2. Docker Compose (tout intégré)"
echo "3. Tests uniquement"
echo ""

# For quick reference, show the commands:

echo "📋 OPTION 1 - Développement Local"
echo "=================================="
echo ""
echo "Terminal 1 - Frontend:"
echo "  npm install --legacy-peer-deps"
echo "  npm start"
echo "  # Ouvert sur http://localhost:8080"
echo ""
echo "Terminal 2 - Backend:"
echo "  cd server"
echo "  npm install --legacy-peer-deps"
echo "  npm run dev"
echo "  # Ouvert sur http://localhost:4000"
echo ""
echo "Terminal 3 - MongoDB (si local):"
echo "  mongod"
echo ""

echo "📋 OPTION 2 - Docker Compose (Recommandé)"
echo "=========================================="
echo ""
echo "  docker-compose up"
echo "  # Frontend: http://localhost:8080"
echo "  # Backend: http://localhost:4000"
echo "  # MongoDB: localhost:27017"
echo ""

echo "📋 OPTION 3 - Tests Backend"
echo "============================"
echo ""
echo "  cd server"
echo "  npm test"
echo ""
echo "  # Ou avec MongoDB externe:"
echo "  TEST_MONGODB_URI=mongodb://localhost:27017/test npm test"
echo ""

echo "🔐 Configuration Requise"
echo "======================="
echo ""
echo "1. Créer .env dans server/ :"
echo "  cp server/.env.example server/.env"
echo ""
echo "2. Éditer server/.env avec:"
echo "  - MONGODB_URI"
echo "  - JWT_SECRET (générer avec: openssl rand -base64 32)"
echo "  - STRIPE_SECRET (pour paiements)"
echo "  - MAIL_USER/PASSWORD (pour emails - optionnel en dev)"
echo ""

echo "📊 URLs Importantes"
echo "==================="
echo ""
echo "Frontend:"
echo "  - Accueil: http://localhost:8080/"
echo "  - Mon compte: http://localhost:8080/account"
echo "  - Dashboard vendeur: http://localhost:8080/seller/dashboard"
echo "  - Dashboard admin: http://localhost:8080/admin/dashboard"
echo ""
echo "Backend API:"
echo "  - Produits: http://localhost:4000/api/products"
echo "  - Commandes: http://localhost:4000/api/orders"
echo "  - Notifications: http://localhost:4000/api/notifications"
echo ""

echo "📚 Documentation"
echo "================"
echo ""
echo "  - README.md - Vue d'ensemble complet"
echo "  - IMPLEMENTATION_SUMMARY.md - Ce qui a été implémenté"
echo "  - server/API_DOCS.md - Documentation API complète"
echo "  - DEPLOYMENT.md - Guide de déploiement production"
echo ""

echo "🧪 Rôles de Test"
echo "================"
echo ""
echo "Pour tester, créer des comptes:"
echo ""
echo "Admin:"
echo "  Email: admin@test.com"
echo "  Password: password123"
echo "  Role: admin"
echo ""
echo "Vendeur:"
echo "  Email: seller@test.com"
echo "  Password: password123"
echo "  Role: seller"
echo ""
echo "Client:"
echo "  Email: client@test.com"
echo "  Password: password123"
echo "  Role: client"
echo ""

echo "⚠️ Troubleshooting"
echo "=================="
echo ""
echo "Erreur: 'Cannot find module'"
echo "  → npm install --legacy-peer-deps"
echo ""
echo "Erreur: 'ECONNREFUSED localhost:27017'"
echo "  → Démarrer MongoDB: mongod"
echo "  → Ou utiliser TEST_MONGODB_URI=... pour tests"
echo ""
echo "Erreur: 'Port already in use'"
echo "  → Changer PORT dans .env"
echo "  → Ou arrêter le processus: lsof -i :4000 | kill"
echo ""

echo "✅ Prêt à commencer! 🎉"
